FROM php:7.2.10-apache

RUN apt-get update && apt-get install -y \
    mysql-client libmagickwand-dev git zip unzip supervisor --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-install pdo_mysql mbstring xml json tokenizer zip

RUN apt-get install --no-install-recommends --assume-yes --quiet ca-certificates curl git &&\
    rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug-2.6.1 && docker-php-ext-enable xdebug
RUN echo 'zend_extension="/usr/local/lib/php/extensions/.so"' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_handler=dbgp' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_mode=req' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_host=10.0.75.0' >> /usr/local/etc/php/php.ini

WORKDIR /var/www

RUN curl --silent --show-error https://getcomposer.org/installer | php
RUN mv /var/www/composer.phar /usr/local/bin/composer

ADD ./apache.conf /etc/apache2/sites-available
ADD ./tmpr.ini /usr/local/etc/php/conf.d/tmpr.ini

RUN a2dissite 000-default.conf
RUN a2ensite apache.conf
RUN a2enmod rewrite

ADD ./ /var/www
RUN composer install
RUN chown -R www-data:www-data .